/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lleoc
 */
public class WeightedDirectedGraph extends javax.swing.JFrame {

    /**
     * Creates new form WeightedDirectedGraph
     */
    public WeightedDirectedGraph() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DepartureAirportJLabel = new javax.swing.JLabel();
        ArrivalAirportJLabel = new javax.swing.JLabel();
        DistanceJLabel = new javax.swing.JLabel();
        AddNewFlightJButton = new javax.swing.JButton();
        SeekFlightJButton = new javax.swing.JButton();
        DeleteFlightJButton = new javax.swing.JButton();
        ExitJButton = new javax.swing.JButton();
        DepartureAirportJTextField = new javax.swing.JTextField();
        ArrivalAirportJTextField = new javax.swing.JTextField();
        DistanceJTextField = new javax.swing.JTextField();
        FlightScheduleJPanel = new javax.swing.JPanel();
        FlightInformationJPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("United States Travel Search");
        setFont(new java.awt.Font("Agency FB", 1, 12)); // NOI18N

        DepartureAirportJLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DepartureAirportJLabel.setText("Departure Airport");

        ArrivalAirportJLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ArrivalAirportJLabel.setText("Arrival Airport");

        DistanceJLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DistanceJLabel.setText("Distance");

        AddNewFlightJButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AddNewFlightJButton.setText("Add New Flight");

        SeekFlightJButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        SeekFlightJButton.setText("Seek Flight");

        DeleteFlightJButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DeleteFlightJButton.setText("Delete Flight");

        ExitJButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ExitJButton.setText("Exit");

        FlightScheduleJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Flight Schedule", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        javax.swing.GroupLayout FlightScheduleJPanelLayout = new javax.swing.GroupLayout(FlightScheduleJPanel);
        FlightScheduleJPanel.setLayout(FlightScheduleJPanelLayout);
        FlightScheduleJPanelLayout.setHorizontalGroup(
            FlightScheduleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        FlightScheduleJPanelLayout.setVerticalGroup(
            FlightScheduleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );

        FlightInformationJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Flight Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        javax.swing.GroupLayout FlightInformationJPanelLayout = new javax.swing.GroupLayout(FlightInformationJPanel);
        FlightInformationJPanel.setLayout(FlightInformationJPanelLayout);
        FlightInformationJPanelLayout.setHorizontalGroup(
            FlightInformationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        FlightInformationJPanelLayout.setVerticalGroup(
            FlightInformationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(FlightScheduleJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AddNewFlightJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SeekFlightJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ArrivalAirportJLabel)
                    .addComponent(DepartureAirportJLabel)
                    .addComponent(DistanceJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(DeleteFlightJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ExitJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(DepartureAirportJTextField)
                    .addComponent(ArrivalAirportJTextField)
                    .addComponent(DistanceJTextField)
                    .addComponent(FlightInformationJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(DepartureAirportJLabel)
                                    .addComponent(DepartureAirportJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(ArrivalAirportJLabel))
                            .addComponent(ArrivalAirportJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(DistanceJLabel))
                    .addComponent(DistanceJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FlightScheduleJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FlightInformationJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddNewFlightJButton)
                    .addComponent(SeekFlightJButton)
                    .addComponent(DeleteFlightJButton)
                    .addComponent(ExitJButton))
                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WeightedDirectedGraph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WeightedDirectedGraph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WeightedDirectedGraph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WeightedDirectedGraph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WeightedDirectedGraph().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddNewFlightJButton;
    private javax.swing.JLabel ArrivalAirportJLabel;
    private javax.swing.JTextField ArrivalAirportJTextField;
    private javax.swing.JButton DeleteFlightJButton;
    private javax.swing.JLabel DepartureAirportJLabel;
    private javax.swing.JTextField DepartureAirportJTextField;
    private javax.swing.JLabel DistanceJLabel;
    private javax.swing.JTextField DistanceJTextField;
    private javax.swing.JButton ExitJButton;
    private javax.swing.JPanel FlightInformationJPanel;
    private javax.swing.JPanel FlightScheduleJPanel;
    private javax.swing.JButton SeekFlightJButton;
    // End of variables declaration//GEN-END:variables
}
